name: CI/CD Pipeline for Docker to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo EXPO_PUBLIC_BACKEND_SERVER=${{ secrets.BACKEND_SERVER }} >> .env
          

      # 2. Docker 로그인 (Docker Hub 사용 시)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t seungwoo08/anywhere2:latest .
          docker push seungwoo08/anywhere2:latest
          
      # 7. AWS EC2에 배포 및 앱 실행
      - name: Deploy and Start App on AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 이전 컨테이너 중지 및 제거
            docker stop anywhere2 || true
            docker rm anywhere2 || true
            
            # 최신 이미지 가져오기
            docker pull seungwoo08/anywhere2:latest
            
            # Expo 앱을 EC2에서 실행하며 포트 매핑
            docker run -d -p 80:3000 --name anywhere2 seungwoo08/anywhere2:latest
            
            
