name: CI/CD Pipeline for Docker to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          npm install

      # 4. Expo 앱 빌드 (웹용으로)
      - name: Build Expo app
        run: npx expo export:web

      # 5. Docker 로그인 (Docker Hub 사용 시)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub Secrets에서 Docker Hub 사용자명
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub Secrets에서 Docker Hub 비밀번호

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          docker build -t seungwoo08/anywhere:latest 
          docker push seungwoo08/anywhere:latest     

      # 7. AWS EC2에 배포
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}             # GitHub Secrets에서 EC2 호스트 IP 또는 DNS
          username: ${{ secrets.EC2_USER }}         # GitHub Secrets에서 EC2 사용자명
          key: ${{ secrets.EC2_SSH_KEY }}           # GitHub Secrets에서 EC2 SSH 키
          script: |
       
            docker pull seungwoo08/anywhere:latest    

        
            docker stop anywhere || true
            docker rm anywhere || true

         
            docker run -d -p 80:3000 --name anywhere seungwoo08/anywhere:latest
